import SignIn from '@/Components/SignIn/SignIn'
import React from 'react'
export const metadata = {
  title: "E-Learning site | Sign In Page",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <SignIn />
  
  </>
}

export default page