import React from 'react'
import Courses from '../../Components/Courses/Courses'
export const metadata = {
  title: "E-Learning | Our Courses",
  description: "Generated by create next app",
};
const page = () => {
  return<>
  <Courses/>
  </>
}

export default page