import Contact from '@/Components/Contact/Contact'
import React from 'react'
export const metadata = {
  title: "E-Learning | Contact Us",
  description: "Generated by create next app",
};
const Page = () => {
  return (
    <Contact />
  )
}

export default Page