import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import Up from "@/Components/Up/Up";



export const metadata = {
  title: "E-Learning site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        <Header/>
        <Up />
        {children}
        <Toaster />

        <Footer/>
      </body>
    </html>
  );
}
