import FeedBack from "@/Components/FeedBack/FeedBack";
import Home from "@/Components/Home/Home";
import PopularCourses from "@/Components/PopularCourses/PopularCourses";
import SemiAbout from "@/Components/SemiAbout/SemiAbout";
export const metadata = {
  title: "E-Learning | Home page",
  description: "Generated by create next app",
};
export default function page() {
  return <>
<Home />
<PopularCourses />
<SemiAbout />
<FeedBack />
  </>
}
