import React from 'react'
import SignUp from "../../Components/SignUp/SignUp"


export const metadata = {
  title: "E-Learning | Sign up ",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <SignUp />
  </>
}

export default page